<a href="https://colab.research.google.com/github/Felife11/SkillTreePython-DataAnalysis/blob/main/05.%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D%EA%B8%B0%EB%B0%98%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B6%84%EC%84%9D/ch05_01_%EA%B8%B0%EC%B4%88%EC%88%98%ED%95%99_%EB%B2%A1%ED%84%B0%EC%99%80%ED%96%89%EB%A0%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ch05.01. 기초수학 - 벡터와 행렬
---
* 날짜: 2022-06-15
* 이름: 정성대

## 학습내용
    - 스칼라, 벡터, 행렬에 대한 기본 개념을 배운다
    - 벡터의 연산에 대해 이해한다
    - 행렬의 연산에 대해 이해한다.


**라이브러리 임포트**
```
import numpy as np
import matplotlib.pyplot as plt
```


In [1]:
# test
import numpy as np # 수학, 데이터, 과학 연산 수행
import matplotlib.pyplot as plt # 파이썬에서 플롯 (근본) 라이브러리

## 스칼라
---

* Zeros-order Tensor Operations


\begin{split}
\begin{align}
\ \ a, b ∈ℝ
\\
\end{align}
\end{split}

\begin{align}
\\
\end{align}
### **| 스칼라 연산**

\begin{split}
\begin{align}
\\ a+b ∈ℝ 
\\ a-b ∈ℝ
\\ a×b ∈ℝ
\end{align}
\end{split}

## 벡터
---
* First-order Tensor Operation


\begin{split}
\begin{align}
𝐱 =
\begin{bmatrix}
x_1 \\
x_2 \\
... \\
x_N \\
\end{bmatrix}
, \ \ \ 
𝐱^T =[ x_1, x_2, ..., x_N]
\ \ \, ∈ℝ^N \ (ℝ^{N\times 1})
\end{align}
\end{split}



### **| 벡터와 벡터의 연산**

\begin{split}
\begin{align}
𝐱 + 𝐲 =
\begin{bmatrix}
x_1 \\
x_2 \\
... \\
x_N \\
\end{bmatrix}
+
\begin{bmatrix}
y_1 \\
y_2 \\
... \\
y_N \\
\end{bmatrix}
=
\begin{bmatrix}
x_1 + y_1 \\
x_2 + y_2  \\
... \\
x_N + y_N \\
\end{bmatrix}
\end{align}
\end{split}

\\

\begin{split}
\begin{align}
𝐱 - 𝐲 =
\begin{bmatrix}
x_1 \\
x_2 \\
... \\
x_N \\
\end{bmatrix}
-
\begin{bmatrix}
y_1 \\
y_2 \\
... \\
y_N \\
\end{bmatrix}
=
\begin{bmatrix}
x_1 - y_1 \\
x_2 - y_2  \\
... \\
x_N - y_N \\
\end{bmatrix}
\end{align}
\end{split}

\\

\begin{split}
\begin{align}
𝐱^T𝐲 = 𝐱^T ⋅ 𝐲 = <𝐱,𝐲> = 
\begin{bmatrix}
x_{1} & x_{2} & \cdots & x_{N} 
\end{bmatrix}
\begin{bmatrix}
y_{1} \\
y_{2} \\
\vdots \\
y_{N} \\
\end{bmatrix} 
= x_1 y_1 + \cdots + x_N y_N 
=\sum_{i=1}^N x_i y_i
\end{align}
\end{split}
\\



#### **예제 01**

\begin{split}
\begin{align}
𝐱=
\begin{bmatrix}
2 \\
1 \\
2 \\
0 \\
\end{bmatrix}
,\;\;
𝐲=
\begin{bmatrix}
1 \\
1 \\
2 \\
4 \\
\end{bmatrix}
\end{align}
\end{split}

In [2]:
x = np.array([2,1,2,0])
y = np.array([1,1,2,4])
print(x.shape, y.shape)

(4,) (4,)


#### **예제 02**

**예제 01**의 𝐱, 𝐲 에 대해 다음 연산을 진행하세요.

* 𝐱 + 𝐲
* 𝐱 - 𝐲
* 𝐱 ⋅ 𝐲
* 𝐱𝐲 (넘파이 브로드 케스팅 연산)

In [7]:
print('x+y', x+y)
print('x-y', x-y)
print('x*y', x*y)
print('x.y', np.dot(x,y))

x+y [3 2 4 4]
x-y [ 1  0  0 -4]
x*y [2 1 4 0]
x.y 7



### **| 벡터와 스칼라의 연산**

\begin{split}
\begin{align}
c𝐱 =
c
\begin{bmatrix}
x_1 \\
x_2 \\
... \\
x_N \\
\end{bmatrix}
=
\begin{bmatrix}
cx_1  \\
cx_2  \\
... \\
cx_N  \\
\end{bmatrix}
\end{align}
\end{split}


* 브로드 캐스팅

원래 덧셈과 뺄셈은 크기가 같은 두 벡터에 대해서만 할 수 있지만 벡터와 스칼라의 경우에는 관례적으로 다음과 같이 스칼라 값을 벡터로 변환하여 연산을 수행합니다.  이를 브로드 캐스팅(broad casting) 이라고 합니다.

\begin{split}
\begin{align}
c+𝐱 =
\begin{bmatrix}
c \\
c \\
... \\
c \\
\end{bmatrix}
+
\begin{bmatrix}
x_1 \\
x_2 \\
... \\
x_N \\
\end{bmatrix}
=
\begin{bmatrix}
c+x_1  \\
c+x_2  \\
... \\
c+x_N  \\
\end{bmatrix}
\end{align}
\end{split}

\\

\begin{split}
\begin{align}
c-𝐱 =
\begin{bmatrix}
c \\
c \\
... \\
c \\
\end{bmatrix}
-
\begin{bmatrix}
x_1 \\
x_2 \\
... \\
x_N \\
\end{bmatrix}
=
\begin{bmatrix}
c-x_1  \\
c-x_2  \\
... \\
c-x_N  \\
\end{bmatrix}
\end{align}
\end{split}

#### **예제 03**

\begin{split}
\begin{align}
𝐱=
\begin{bmatrix}
10 \\
11 \\
12 \\
\end{bmatrix}
,\;\;
𝐲=
\begin{bmatrix}
0 \\
1 \\
2 \\
\end{bmatrix}
, \; c = 2
\end{align}
\end{split}




* 𝐱, 𝐲, c 정의하기

In [38]:
x = np.array([10,11,12])
print(x.shape)
x2 = np.array([[10,11,12]])
print(x2.shape)
x3 = np.array([[10],[11],[12]]) 
print(x3.shape)
print(x.T)
print(x)

(3,)
(1, 3)
(3, 1)
[10 11 12]
[10 11 12]


In [10]:
x = np.array([10,11,12])
y = np.array([10,1,2])
c=2
print(x.shape, y.shape,)

(3,) (3,)


* $c𝐱-𝐲$ 

In [12]:
print('cx-y', c*x-y)

cx-y [20 21 22]


* $𝐱^T𝐲$

In [17]:
print('Xty', x.T*y)


Xty [ 0 11 24]


* $2c𝐱+𝐲$

In [18]:
print('2cx+y', 2*c*x + y)

2cx+y [40 45 50]


#### **예제 04**

도매로 A, B, C 세개의 물건을 사려 하는데 한 박스당 각각 10만원, 12만원, 20만원입니다. 각각 총 5박스, 8박스, 4박스를 사려고 합니다. 

(1) 박스가격과 구매 수량을 각각 p 벡터, n 벡터로 표시하고 넘파이로 코딩합니다.

(2) 물건을 구입할 때 드는 총 비용을 계산하세요.

In [23]:
p = np.array([10,12,20])
n = np.array([5,8,4])
print("price", p*n)

price [50 96 80]


#### **예제 05**

(1) 국어, 수학, 사회, 과학, 영어 의 시험 성적이 각각 70, 100, 90, 70, 50 입니다. 성적을 벡터 x 로 표시하고 넘파이로 코딩합니다.

(2) 문과에서 과목별 가중치는 각각 0.25, 0.2, 0.2, 0.1, 0.25 입니다. 가중치를 벡터 w1 로 표시하고 넘파이로 코딩합니다.

(3) 이과에서 과목별 가중치는 각각 0.15, 0.4, 0.1, 0.2, 0.15 입니다. 가중치를 벡터 w2 로 표시하고 넘파이로 코딩합니다.

(4) 문과 가중치와 이과 가중치를 적용해서 성적의 총합을 계산하고 어떤 과를 가는게 유리한지 적으세요.

In [32]:
x = np.array([70,100,90,70,50])
w1 = np.array([0.25,0.2,0.2,0.1,0.25])
w2 = np.array([0.15,0.4,0.1,0.2,0.15])
print("문과", x*w1)
print("문과", np.dot(x,w1))
print("이과", x*w2)
print("이과", np.dot(x,w2))

문과 [17.5 20.  18.   7.  12.5]
문과 75.0
이과 [10.5 40.   9.  14.   7.5]
이과 81.0


## 행렬
---

* Second-order Tensor Operation

\begin{split}
\begin{align}
A=
\begin{bmatrix}
a_{11} \ \ \ a_{12} \ \ \ ... \ \ \ a_{1M} \\
a_{21} \ \ \ a_{22} \ \ \ ... \ \ \ a_{2M} \\
... \ \ \ ... \ \ \ ... \ \ \ ... \\
... \ \ \ ... \ \ \ a_{ij} \ \ \ ... \\
... \ \ \ ... \ \ \ ... \ \ \ ... \\
a_{N1} \ \ \ a_{N2} \ \ \ ... \ \ \ a_{NM} \\
\end{bmatrix}
\ \ , \ \ A∈ℝ^{N\times M}
\end{align}
\end{split}




### **| 행렬과 행렬의 연산**


* 덧셈, 뺄셈

\begin{align}
A+(-)B=
\begin{bmatrix}
a_{11} \ \ \ a_{12} \ \ \ ... \ \ \ a_{1M} \\
a_{21} \ \ \ a_{22} \ \ \ ... \ \ \ a_{2M} \\
... \ \ \ ... \ \ \ ... \ \ \ ... \\
... \ \ \ ... \ \ \ a_{ij} \ \ \ ... \\
... \ \ \ ... \ \ \ ... \ \ \ ... \\
a_{N1} \ \ \ a_{N2} \ \ \ ... \ \ \ a_{NM} \\
\end{bmatrix}
+(-)
\begin{bmatrix}
b_{11} \ \ \ b_{12} \ \ \ ... \ \ \ b_{1M} \\
b_{21} \ \ \ b_{22} \ \ \ ... \ \ \ b_{2M} \\
... \ \ \ ... \ \ \ ... \ \ \ ... \\
... \ \ \ ... \ \ \ b_{ij} \ \ \ ... \\
... \ \ \ ... \ \ \ ... \ \ \ ... \\
b_{N1} \ \ \ b_{N2} \ \ \ ... \ \ \ b_{NM} \\
\end{bmatrix}
\end{align}
\begin{align}
\\
\\
A∈ℝ^{N\times M} \ \ \ \ B∈ℝ^{N\times M}
\\
\\
\end{align}




* 곱셈

\begin{align}
\\
\\
A \ \ \ \ \ \ \times \ \ \ \ \ \ B \ \ \ \ \ \ =  \ \ \ \ \ C \\
\\
ℝ^{N\times M} \ \ \ \ \ \ \ \ \ ℝ^{M\times K} \  \ \ \ \ \ \ \ ℝ^{N\times K}
\end{align}




### **| 행렬과 벡터의 연산**

* 곱셈

\begin{align}
\\
\\
A \ \ \ \ \ \ \times \ \ \ \ \ \ 𝐱 \ \ \ \ \ \ =  \ \ \ \ \ A𝐱 \\
\\
ℝ^{N\times M} \ \ \ \ \ \ \ \ \ ℝ^{M\times 1} \  \ \ \ \ \ \ \ ℝ^{N\times 1}
\end{align}


#### **예제 06**

\begin{split}
\begin{align}
A=
\begin{bmatrix}
1 \ \ \ 1 \ \ \ 0 \ \ \ 0 \\
2 \ \ \ 0 \ \ \ 0 \ \ \ 1 \\
0 \ \ \ 1 \ \ \ 0 \ \ \ 1 \\
\end{bmatrix}
\end{align}
\end{split}

* $A$를 정의하세요.

In [41]:
A = np.array([ [1,1,0,0],
               [2,0,0,1], 
               [0,1,0,1] ])
# (3, 4)
print(A.shape)

(3, 4)


* $A∈ℝ^{N\times M}$ 에서 N과 M을 구하세요.

In [42]:
#R 은 실수 집합
# N : 3
# M : 4

In [44]:
#행렬곱 : @
print(A.T) # A transpose
print(A) # A
print(A.T@A) # 행렬곱

[[1 2 0]
 [1 0 1]
 [0 0 0]
 [0 1 1]] [[1 1 0 0]
 [2 0 0 1]
 [0 1 0 1]]
[[1 1 0 0]
 [2 0 0 1]
 [0 1 0 1]]
[[5 1 0 2]
 [1 2 0 1]
 [0 0 0 0]
 [2 1 0 2]]


#### **예제 07**

\begin{split}
\begin{align}
A =
\begin{bmatrix}
1 \ \ 2 \ \ 3 \\
4 \ \ 5 \ \ 6 \\
\end{bmatrix}
B =
\begin{bmatrix}
1 \ \ 0 \ \ 0 \\
0 \ \ 1 \ \ 0 \\
0 \ \ 0 \ \ 1 \\
\end{bmatrix}
,\;\;
𝐱=
\begin{bmatrix}
0 \\
1 \\
2 \\
\end{bmatrix}
, \; c = 2
\end{align}
\end{split}




* $A, B, 𝐱, c$ 정의하기

In [56]:
A = np.array([[1,2,3], [4,5,6]])
print(A.shape)
B = np.array([[1,0,0], [0,1,0], [0,0,1]])
print(B.shape)
x = np.array([[0],[1],[2]])
print(x.shape)
print(x.T)
print(x.T.shape)
c =2

(2, 3)
(3, 3)
(3, 1)
[[0 1 2]]
(1, 3)


* $cAB$ 을 계산하고 ℝ 의 변화를 쓰세요.

In [47]:
print("cAB : ", c*A@B) # (2,3) * (3,3) = (2,3) 

cAB [[ 2  4  6]
 [ 8 10 12]]


* $AB𝐱$

In [52]:
print("ABx : ", A@B@x) # (2,3) * (3,3 )* (3,1) = (2,1)

ABx :  [[ 8]
 [17]]


* $𝐱^TBA^T$ 을 계산하고 ℝ 의 변화를 쓰세요.

In [54]:
print("xTBAT",x.T @ B @A.T ) #(1,3) * (3,3) * (3,2) = (1,2)

xTBAT [[ 8 17]]


#### **예제 08**

행렬 $A$가 다음과 같이 주어졌을 때 $AB$ 행렬이 각 shape를 만족하도록 $B$를 정의하세요. 단 $B$의 값은 1부터 5까지 랜덤 정수 입니다.

\begin{split}
\begin{align}
A =
\begin{bmatrix}
1 \ \ 1 \ \ 1 \ \ 1 \\
2 \ \ 2 \ \ 2 \ \ 2 \\
\end{bmatrix}
\end{align}
\end{split}






* $A$ 정의하기

In [59]:
A = np.array([[1,1,1,1], [2,2,2,2]])
print(A.shape)
print(A)

(2, 4)
[[1 1 1 1]
 [2 2 2 2]]


* $AB \in ℝ^{2\times5}$ 일 때 $B$를 정의하고 $AB$를 계산하세요.

In [63]:
B = np.array([[1,1,1,1,1], [0,0,0,0,0], [1,1,1,1,1], [0,0,0,0,0]])
print(B.shape)
print(B)
print("AB", A@B)

(4, 5)
[[1 1 1 1 1]
 [0 0 0 0 0]
 [1 1 1 1 1]
 [0 0 0 0 0]]
AB [[2 2 2 2 2]
 [4 4 4 4 4]]


* $AB \in ℝ^{2\times3}$ 일 때 $B$를 정의하고 $AB$를 계산하세요.

In [64]:
B = np.array([[1,1,1], [0,0,0], [1,1,1], [0,0,0]])
print(B.shape)
print(B)
print("AB", A@B)

(4, 3)
[[1 1 1]
 [0 0 0]
 [1 1 1]
 [0 0 0]]
AB [[2 2 2]
 [4 4 4]]


* $AB \in ℝ^{2\times1}$ 일 때 $B$를 정의하고 $AB$를 계산하세요.

In [70]:
B = np.array([[1],[0],[1],[0]])
print(B.shape)
print(B)
print("AB", A@B)

(4, 1)
[[1]
 [0]
 [1]
 [0]]
AB [[2]
 [4]]


* $A$와 $M$ 두개의 값을 인풋으로 하면 $AB \in ℝ^{N\times M}$를 만족하는 랜덤행렬 $B$를 반환하도록 함수 `random_weights`를 생성하세요.

In [72]:
B = random_weights(A, 5)
print(A.shape, B.shape, (A@B).shape)

NameError: ignored

* 함수 사용 예시

In [ ]:
B = random_weights(A, 5)
print(A.shape, B.shape, (A@B).shape)

(2, 4) (4, 5) (2, 5)
